export interface AnalysisPattern {
  quotientId: string;
  keywords: string[];
  sentimentIndicators: string[];
  behavioralMarkers: string[];
  questionPatterns: string[];
}

export const ANALYSIS_PATTERNS: AnalysisPattern[] = [
  {
    quotientId: 'iq',
    keywords: [
      'understand',
      'analyze',
      'logic',
      'reason',
      'think',
      'problem',
      'solve',
      'learn',
      'complex',
      'abstract',
      'pattern',
      'strategy',
      'calculate',
    ],
    sentimentIndicators: [
      'I need to understand why',
      'Let me think about this logically',
      "I'm trying to figure out",
      "What's the reasoning behind",
      'I want to analyze',
    ],
    behavioralMarkers: [
      'Asks analytical questions',
      'Seeks logical explanations',
      'Discusses complex topics',
      'Shows pattern recognition',
      'Uses precise language',
    ],
    questionPatterns: [
      'How does this work?',
      "What's the logic behind?",
      'Can you explain the reasoning?',
      'What are the patterns here?',
    ],
  },
  {
    quotientId: 'eq',
    keywords: [
      'feel',
      'emotion',
      'relationship',
      'empathy',
      'understand others',
      'connect',
      'sensitive',
      'aware',
      'mood',
      'stress',
      'anxiety',
      'happy',
      'sad',
      'angry',
      'frustrated',
      'overwhelmed',
      'lonely',
    ],
    sentimentIndicators: [
      'I feel',
      "I'm struggling with",
      "I'm worried about",
      "I don't understand why I",
      "I can't seem to",
      'Others make me feel',
      "I'm having trouble with people",
    ],
    behavioralMarkers: [
      'Discusses feelings openly',
      'Shows empathy for others',
      'Mentions relationship issues',
      'Expresses emotional awareness',
      'Seeks emotional understanding',
    ],
    questionPatterns: [
      'Why do I feel this way?',
      'How can I handle my emotions?',
      'How do I deal with others?',
      "Why don't people understand me?",
    ],
  },
  {
    quotientId: 'aq',
    keywords: [
      'challenge',
      'difficult',
      'obstacle',
      'failure',
      'setback',
      'struggle',
      'overcome',
      'give up',
      'quit',
      'persevere',
      'resilient',
      'tough',
      'hard',
      'impossible',
      "can't",
      "won't",
    ],
    sentimentIndicators: [
      'I keep failing at',
      'I want to give up',
      'Everything is going wrong',
      "I can't overcome",
      "I'm stuck",
      'Nothing works',
      "I've tried everything",
    ],
    behavioralMarkers: [
      'Discusses past failures',
      'Shows defeatist attitude',
      'Mentions giving up',
      'Expresses frustration with obstacles',
      'Seeks help with persistence',
    ],
    questionPatterns: [
      'How do I keep going?',
      'What do I do when I fail?',
      'How can I overcome this?',
      'Should I give up?',
    ],
  },
  {
    quotientId: 'sq',
    keywords: [
      'people',
      'social',
      'friends',
      'relationship',
      'network',
      'communicate',
      'talk',
      'conversation',
      'awkward',
      'shy',
      'introverted',
      'lonely',
      'connect',
      'team',
      'group',
      'party',
      'meeting',
    ],
    sentimentIndicators: [
      'I struggle to make friends',
      "I don't know what to say",
      'I feel awkward in social situations',
      "People don't understand me",
      "I'm not good with people",
      'I prefer being alone',
    ],
    behavioralMarkers: [
      'Discusses social difficulties',
      'Mentions loneliness',
      'Expresses social anxiety',
      'Seeks advice on relationships',
      'Talks about communication issues',
    ],
    questionPatterns: [
      'How do I make friends?',
      'What should I say to people?',
      'How can I be more social?',
      'Why am I so awkward?',
    ],
  },
  {
    quotientId: 'cq',
    keywords: [
      'creative',
      'idea',
      'innovative',
      'original',
      'imagine',
      'design',
      'art',
      'music',
      'write',
      'create',
      'invent',
      'unique',
      'different',
      'boring',
      'routine',
      'same',
    ],
    sentimentIndicators: [
      'I want to create something',
      'I have an idea',
      "I'm feeling uninspired",
      'Everything feels boring',
      'I need something new',
      'I want to express myself',
    ],
    behavioralMarkers: [
      'Discusses creative pursuits',
      'Mentions artistic interests',
      'Seeks novel solutions',
      'Expresses desire for originality',
      'Talks about innovation',
    ],
    questionPatterns: [
      'How can I be more creative?',
      'How do I come up with ideas?',
      'How can I think differently?',
      'How do I express myself?',
    ],
  },
  {
    quotientId: 'mq',
    keywords: [
      'right',
      'wrong',
      'ethical',
      'moral',
      'values',
      'integrity',
      'honest',
      'fair',
      'justice',
      'principle',
      'should',
      'ought',
      'guilty',
      'shame',
    ],
    sentimentIndicators: [
      "I don't know if this is right",
      'I feel guilty about',
      "I'm not sure what's ethical",
      "I'm struggling with a moral dilemma",
      'I want to do the right thing',
    ],
    behavioralMarkers: [
      'Discusses ethical dilemmas',
      'Mentions values and principles',
      'Expresses moral concerns',
      'Seeks guidance on right/wrong',
      'Shows concern for fairness',
    ],
    questionPatterns: [
      'Is this the right thing to do?',
      'What should I do ethically?',
      'How do I handle this morally?',
      'What are my values?',
    ],
  },
  {
    quotientId: 'lq',
    keywords: [
      'learn',
      'study',
      'education',
      'skill',
      'knowledge',
      'course',
      'book',
      'teach',
      'practice',
      'improve',
      'develop',
      'grow',
      'master',
      'curious',
    ],
    sentimentIndicators: [
      'I want to learn',
      "I'm curious about",
      "I don't know how to",
      'I need to improve',
      'I want to develop',
      "I'm interested in learning",
    ],
    behavioralMarkers: [
      'Asks many questions',
      'Shows curiosity',
      'Discusses learning goals',
      'Mentions skill development',
      'Expresses desire to improve',
    ],
    questionPatterns: [
      'How can I learn?',
      'What should I study?',
      'How do I improve at?',
      'Where can I learn about?',
    ],
  },
  {
    quotientId: 'vq',
    keywords: [
      'goal',
      'future',
      'vision',
      'dream',
      'aspire',
      'plan',
      'direction',
      'purpose',
      'ambition',
      'long-term',
      'career',
      'life',
      'success',
    ],
    sentimentIndicators: [
      "I don't know what I want",
      "I'm not sure where I'm going",
      'I need direction',
      'I want to achieve',
      'My goal is',
      'I dream of',
    ],
    behavioralMarkers: [
      'Discusses future plans',
      'Mentions goals and aspirations',
      'Seeks direction',
      'Expresses ambition',
      'Talks about purpose',
    ],
    questionPatterns: [
      'What should my goals be?',
      'Where am I going in life?',
      "What's my purpose?",
      'How do I plan my future?',
    ],
  },
  {
    quotientId: 'rq',
    keywords: [
      'stress',
      'burnout',
      'overwhelmed',
      'exhausted',
      'tired',
      'cope',
      'recover',
      'balance',
      'self-care',
      'mental health',
      'anxiety',
      'pressure',
    ],
    sentimentIndicators: [
      "I'm so stressed",
      "I'm burned out",
      "I can't handle",
      "I'm overwhelmed",
      'I need a break',
      "I'm exhausted",
    ],
    behavioralMarkers: [
      'Discusses stress and pressure',
      'Mentions burnout symptoms',
      'Expresses feeling overwhelmed',
      'Seeks stress management advice',
      'Talks about mental health',
    ],
    questionPatterns: [
      'How do I handle stress?',
      'How can I recover from burnout?',
      'How do I find balance?',
      'What self-care should I do?',
    ],
  },
  {
    quotientId: 'pq',
    keywords: [
      'passion',
      'love',
      'enjoy',
      'excited',
      'motivated',
      'inspired',
      'enthusiastic',
      'boring',
      'meaningless',
      'purpose',
      'drive',
      'care',
    ],
    sentimentIndicators: [
      "I don't feel passionate about",
      "I've lost my motivation",
      "I don't care about",
      'I want to find my passion',
      'I love doing',
      "I'm excited about",
    ],
    behavioralMarkers: [
      'Discusses lack of motivation',
      'Mentions passion or its absence',
      'Expresses enthusiasm (or lack thereof)',
      'Seeks meaning and purpose',
      'Talks about interests',
    ],
    questionPatterns: [
      'How do I find my passion?',
      'What should I be excited about?',
      'How do I stay motivated?',
      'What gives life meaning?',
    ],
  },
];

export function getPatternsByQuotient(quotientId: string): AnalysisPattern | undefined {
  return ANALYSIS_PATTERNS.find((p) => p.quotientId === quotientId);
}

export function getAllPatterns(): AnalysisPattern[] {
  return ANALYSIS_PATTERNS;
}
